export default [
  {
    name: 'san-antonio',
    images: [
      { src: 'atardecer.jpg', text: '', thumbnail: 'atardecer_thumbnail.jpg' },
      { src: 'biblioteca.jpg', text: '', thumbnail: 'biblioteca_thumbnail.jpg' },
      { src: 'camino.jpg', text: '', thumbnail: 'camino_thumbnail.jpg' },
      { src: 'cristo1.jpg', text: '', thumbnail: 'cristo1_thumbnail.jpg' },
      { src: 'cristo2.jpg', text: '', thumbnail: 'cristo2_thumbnail.jpg' },
      { src: 'cristo3.jpg', text: '', thumbnail: 'cristo3_thumbnail.jpg' },
      { src: 'cristo4.jpg', text: '', thumbnail: 'cristo4_thumbnail.jpg' },
      { src: 'escalera.jpg', text: '', thumbnail: 'escalera_thumbnail.jpg' },
      { src: 'logallardo.jpg', text: '', thumbnail: 'logallardo_thumbnail.jpg' },
      { src: 'piedra.jpg', text: '', thumbnail: 'piedra_thumbnail.jpg' },
      { src: 'plaza1.jpg', text: '', thumbnail: 'plaza1_thumbnail.jpg' },
      { src: 'plaza2.jpg', text: '', thumbnail: 'plaza2_thumbnail.jpg' },
      { src: 'plaza3.jpg', text: '', thumbnail: 'plaza3_thumbnail.jpg' },
      { src: 'plaza4.jpg', text: '', thumbnail: 'plaza4_thumbnail.jpg' },
      { src: 'puente.jpg', text: '', thumbnail: 'puente_thumbnail.jpg' },
      { src: 'santuario.jpg', text: '', thumbnail: 'santuario_thumbnail.jpg' },
      { src: 'tren1.jpg', text: '', thumbnail: 'tren1_thumbnail.jpg' },
      { src: 'tren2.jpg', text: '', thumbnail: 'tren2_thumbnail.jpg' },
    ],
  },
  {
    name: 'puerto',
    images: [
      { src: 'bote.jpg', text: '', thumbnail: 'bote_thumbnail.jpg' },
      { src: 'botes.jpg', text: '', thumbnail: 'botes_thumbnail.jpg' },
      { src: 'gaviota1.jpg', text: '', thumbnail: 'gaviota1_thumbnail.jpg' },
      { src: 'gaviota2.jpg', text: '', thumbnail: 'gaviota2_thumbnail.jpg' },
      { src: 'gaviota3.jpg', text: '', thumbnail: 'gaviota3_thumbnail.jpg' },
      { src: 'gaviota4.jpg', text: '', thumbnail: 'gaviota4_thumbnail.jpg' },
      { src: 'gaviota5.jpg', text: '', thumbnail: 'gaviota5_thumbnail.jpg' },
      { src: 'gaviota6.jpg', text: '', thumbnail: 'gaviota6_thumbnail.jpg' },
      { src: 'terminal.jpg', text: '', thumbnail: 'terminal_thumbnail.jpg' },
    ],
  },
  {
    name: 'hogar',
    images: [
      { src: 'empanadas.jpg', text: '', thumbnail: 'empanadas_thumbnail.jpg' },
      { src: 'malva-rosa.jpg', text: '', thumbnail: 'malva-rosa_thumbnail.jpg' },
      { src: 'malvaviscos.jpg', text: '', thumbnail: 'malvaviscos_thumbnail.jpg' },
      { src: 'pasteles.jpg', text: '', thumbnail: 'pasteles_thumbnail.jpg' },
      { src: 'tetera.jpg', text: '', thumbnail: 'tetera_thumbnail.jpg' },
      { src: 'torta.jpg', text: '', thumbnail: 'torta_thumbnail.jpg' },
      { src: 'troncos.jpg', text: '', thumbnail: 'troncos_thumbnail.jpg' },
      { src: 'vino.jpg', text: '', thumbnail: 'vino_thumbnail.jpg' },
    ],
  },
  {
    name: 'cosas',
    images: [
      { src: 'aros.jpg', text: '', thumbnail: 'aros_thumbnail.jpg' },
      { src: 'eevee.jpg', text: '', thumbnail: 'eevee_thumbnail.jpg' },
      { src: 'erizo.jpg', text: '', thumbnail: 'erizo_thumbnail.jpg' },
    ],
  },
];
