export default [
  {
    name: 'san-antonio',
    images: [
      { src: 'atardecer.jpg', text: '' },
      { src: 'biblioteca.jpg', text: '' },
      { src: 'camino.jpg', text: '' },
      { src: 'cristo1.jpg', text: '' },
      { src: 'cristo2.jpg', text: '' },
      { src: 'cristo3.jpg', text: '' },
      { src: 'cristo4.jpg', text: '' },
      { src: 'escalera.jpg', text: '' },
      { src: 'logallardo.jpg', text: '' },
      { src: 'piedra.jpg', text: '' },
      { src: 'plaza1.jpg', text: '' },
      { src: 'plaza2.jpg', text: '' },
      { src: 'plaza3.jpg', text: '' },
      { src: 'plaza4.jpg', text: '' },
      { src: 'puente.jpg', text: '' },
      { src: 'santuario.jpg', text: '' },
      { src: 'tren1.jpg', text: '' },
      { src: 'tren2.jpg', text: '' },
    ],
  },
  {
    name: 'puerto',
    images: [
      { src: 'bote.jpg', text: '' },
      { src: 'botes.jpg', text: '' },
      { src: 'gaviota1.jpg', text: '' },
      { src: 'gaviota2.jpg', text: '' },
      { src: 'gaviota3.jpg', text: '' },
      { src: 'gaviota4.jpg', text: '' },
      { src: 'gaviota5.jpg', text: '' },
      { src: 'gaviota6.jpg', text: '' },
      { src: 'terminal.jpg', text: '' },
    ],
  },
  {
    name: 'hogar',
    images: [
      { src: 'empanadas.jpg', text: '' },
      { src: 'malva-rosa.jpg', text: '' },
      { src: 'malvaviscos.jpg', text: '' },
      { src: 'pasteles.jpg', text: '' },
      { src: 'tetera.jpg', text: '' },
      { src: 'torta.jpg', text: '' },
      { src: 'troncos.jpg', text: '' },
      { src: 'vino.jpg', text: '' },
    ],
  },
  {
    name: 'cosas',
    images: [
      { src: 'aros.jpg', text: '' },
      { src: 'eevee.jpg', text: '' },
      { src: 'erizo.jpg', text: '' },
    ],
  },
];
