export default [
  {
    name: 'san-antonio',
    images: [
      {
        src: 'atardecer.jpg',
        text: '',
        thumbnail: 'atardecer_thumbnail.jpg',
        placeholder: 'atardecer_placeholder.jpg',
      },
      {
        src: 'biblioteca.jpg',
        text: '',
        thumbnail: 'biblioteca_thumbnail.jpg',
        placeholder: 'biblioteca_placeholder.jpg',
      },
      {
        src: 'camino.jpg',
        text: '',
        thumbnail: 'camino_thumbnail.jpg',
        placeholder: 'camino_placeholder.jpg',
      },
      {
        src: 'cristo1.jpg',
        text: '',
        thumbnail: 'cristo1_thumbnail.jpg',
        placeholder: 'cristo1_placeholder.jpg',
      },
      {
        src: 'cristo2.jpg',
        text: '',
        thumbnail: 'cristo2_thumbnail.jpg',
        placeholder: 'cristo2_placeholder.jpg',
      },
      {
        src: 'cristo3.jpg',
        text: '',
        thumbnail: 'cristo3_thumbnail.jpg',
        placeholder: 'cristo3_placeholder.jpg',
      },
      {
        src: 'cristo4.jpg',
        text: '',
        thumbnail: 'cristo4_thumbnail.jpg',
        placeholder: 'cristo4_placeholder.jpg',
      },
      {
        src: 'escalera.jpg',
        text: '',
        thumbnail: 'escalera_thumbnail.jpg',
        placeholder: 'escalera_placeholder.jpg',
      },
      {
        src: 'logallardo.jpg',
        text: '',
        thumbnail: 'logallardo_thumbnail.jpg',
        placeholder: 'logallardo_placeholder.jpg',
      },
      {
        src: 'piedra.jpg',
        text: '',
        thumbnail: 'piedra_thumbnail.jpg',
        placeholder: 'piedra_placeholder.jpg',
      },
      {
        src: 'plaza1.jpg',
        text: '',
        thumbnail: 'plaza1_thumbnail.jpg',
        placeholder: 'plaza1_placeholder.jpg',
      },
      {
        src: 'plaza2.jpg',
        text: '',
        thumbnail: 'plaza2_thumbnail.jpg',
        placeholder: 'plaza2_placeholder.jpg',
      },
      {
        src: 'plaza3.jpg',
        text: '',
        thumbnail: 'plaza3_thumbnail.jpg',
        placeholder: 'plaza3_placeholder.jpg',
      },
      {
        src: 'plaza4.jpg',
        text: '',
        thumbnail: 'plaza4_thumbnail.jpg',
        placeholder: 'plaza4_placeholder.jpg',
      },
      {
        src: 'puente.jpg',
        text: '',
        thumbnail: 'puente_thumbnail.jpg',
        placeholder: 'puente_placeholder.jpg',
      },
      {
        src: 'santuario.jpg',
        text: '',
        thumbnail: 'santuario_thumbnail.jpg',
        placeholder: 'santuario_placeholder.jpg',
      },
      {
        src: 'tren1.jpg',
        text: '',
        thumbnail: 'tren1_thumbnail.jpg',
        placeholder: 'tren1_placeholder.jpg',
      },
      {
        src: 'tren2.jpg',
        text: '',
        thumbnail: 'tren2_thumbnail.jpg',
        placeholder: 'tren2_placeholder.jpg',
      },
    ],
  },
  {
    name: 'puerto',
    images: [
      {
        src: 'bote.jpg',
        text: '',
        thumbnail: 'bote_thumbnail.jpg',
        placeholder: 'bote_placeholder.jpg',
      },
      {
        src: 'botes.jpg',
        text: '',
        thumbnail: 'botes_thumbnail.jpg',
        placeholder: 'botes_placeholder.jpg',
      },
      {
        src: 'gaviota1.jpg',
        text: '',
        thumbnail: 'gaviota1_thumbnail.jpg',
        placeholder: 'gaviota1_placeholder.jpg',
      },
      {
        src: 'gaviota2.jpg',
        text: '',
        thumbnail: 'gaviota2_thumbnail.jpg',
        placeholder: 'gaviota2_placeholder.jpg',
      },
      {
        src: 'gaviota3.jpg',
        text: '',
        thumbnail: 'gaviota3_thumbnail.jpg',
        placeholder: 'gaviota3_placeholder.jpg',
      },
      {
        src: 'gaviota4.jpg',
        text: '',
        thumbnail: 'gaviota4_thumbnail.jpg',
        placeholder: 'gaviota4_placeholder.jpg',
      },
      {
        src: 'gaviota5.jpg',
        text: '',
        thumbnail: 'gaviota5_thumbnail.jpg',
        placeholder: 'gaviota5_placeholder.jpg',
      },
      {
        src: 'gaviota6.jpg',
        text: '',
        thumbnail: 'gaviota6_thumbnail.jpg',
        placeholder: 'gaviota6_placeholder.jpg',
      },
      {
        src: 'terminal.jpg',
        text: '',
        thumbnail: 'terminal_thumbnail.jpg',
        placeholder: 'terminal_placeholder.jpg',
      },
    ],
  },
  {
    name: 'hogar',
    images: [
      {
        src: 'empanadas.jpg',
        text: '',
        thumbnail: 'empanadas_thumbnail.jpg',
        placeholder: 'empanadas_placeholder.jpg',
      },
      {
        src: 'malva-rosa.jpg',
        text: '',
        thumbnail: 'malva-rosa_thumbnail.jpg',
        placeholder: 'malva-rosa_placeholder.jpg',
      },
      {
        src: 'malvaviscos.jpg',
        text: '',
        thumbnail: 'malvaviscos_thumbnail.jpg',
        placeholder: 'malvaviscos_placeholder.jpg',
      },
      {
        src: 'pasteles.jpg',
        text: '',
        thumbnail: 'pasteles_thumbnail.jpg',
        placeholder: 'pasteles_placeholder.jpg',
      },
      {
        src: 'tetera.jpg',
        text: '',
        thumbnail: 'tetera_thumbnail.jpg',
        placeholder: 'tetera_placeholder.jpg',
      },
      {
        src: 'torta.jpg',
        text: '',
        thumbnail: 'torta_thumbnail.jpg',
        placeholder: 'torta_placeholder.jpg',
      },
      {
        src: 'troncos.jpg',
        text: '',
        thumbnail: 'troncos_thumbnail.jpg',
        placeholder: 'troncos_placeholder.jpg',
      },
      {
        src: 'vino.jpg',
        text: '',
        thumbnail: 'vino_thumbnail.jpg',
        placeholder: 'vino_placeholder.jpg',
      },
    ],
  },
  {
    name: 'cosas',
    images: [
      {
        src: 'aros.jpg',
        text: '',
        thumbnail: 'aros_thumbnail.jpg',
        placeholder: 'aros_placeholder.jpg',
      },
      {
        src: 'eevee.jpg',
        text: '',
        thumbnail: 'eevee_thumbnail.jpg',
        placeholder: 'eevee_placeholder.jpg',
      },
      {
        src: 'erizo.jpg',
        text: '',
        thumbnail: 'erizo_thumbnail.jpg',
        placeholder: 'erizo_placeholder.jpg',
      },
    ],
  },
];
